name: Compilar APK con Cordova
on:
  push:
    branches:
      - main
      - principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo de GitHub
        uses: actions/checkout@v4

      - name: Configurar Node.js en el servidor
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Compilar la pagina web (Vite)
        run: npm run build

      - name: Configurar Java y Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Cordova de forma global
        run: npm install -g cordova

      - name: Crear proyecto Android y configurar XML
        run: |
          cordova create app-android com.documentacionrrbb.asistentebienes "Asistente de Bienes"
          cd app-android
          echo '<?xml version="1.0" encoding="UTF-8"?><widget id="com.documentacionrrbb.asistentebienes" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0"><name>Asistente de Bienes</name><description>App Asistente</description><author email="vmanuelvo@gmail.com">Victor Villena</author><content src="index.html" /><access origin="*" /><allow-intent href="http://*/*" /><allow-intent href="https://*/*" /></widget>' > config.xml
          cordova platform add android
          rm -rf www/*
          cp -r ../dist/* www/
          cordova build android --debug

      - name: Guardar mi archivo APK listo
        uses: actions/upload-artifact@v4
        with:
          name: app-asistente-bienes-instalable
          path: app-android/platforms/android/app/build/outputs/apk/debug/app-debug.apk
